# Generated by Django 2.2.3 on 2019-07-25 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.PositiveSmallIntegerField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER'), (3, 'SUPPLIER'), (4, 'to_be_added_1'), (5, 'to_be_added_2'), (6, 'to_be_added_3'), (7, 'to_be_added_4')])),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date of Registration')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Activity Status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('valid_payment', models.BooleanField(default=False, verbose_name='Payment Information Registration Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='Phone Number')),
                ('bank_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('account_holder_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
            },
        ),
    ]
