# Generated by Django 2.2.3 on 2019-07-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='act_type',
            new_name='acc',
        ),
    ]
