# Generated by Django 2.2.3 on 2019-07-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190705_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acc',
            new_name='acc_type',
        ),
    ]
