# Generated by Django 2.2.3 on 2019-07-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190705_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER'), (3, 'SUPPLIER'), (4, 'to_be_added_1'), (4, 'to_be_added_2'), (4, 'to_be_added_3'), (4, 'to_be_added_4')]),
        ),
    ]
