# Generated by Django 2.2.3 on 2019-07-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190706_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Google'), (2, 'Facebook'), (3, 'Native')], default=3),
        ),
    ]
